edition = "2021"
unstable_features = true
chain_width = 100
wrap_comments = true
comment_width = 100
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
normalize_doc_attributes = true
overflow_delimited_expr = true
report_fixme = "Always"
report_todo = "Always"
tab_spaces = 2
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
